source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '< 5.1'
gem 'puma', '~> 3.0'
gem 'slim-rails'
gem 'pg', '< 1'
gem 'chewy'
gem 'recaptcha'
gem 'bootstrap', '~> 4.0'
gem 'coffee-rails'
gem 'json'
gem 'jquery-rails'
gem 'nokogiri'
