default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: patas_dadas_dev
  username: vagrant
  password: vagrant_pass

test:
  <<: *default
  database: patas_dadas_test
  username: vagrant
  password: vagrant_pass
  
production:
  <<: *default
  database: patas_dadas_production